# Usa la imagen oficial de Node.js
FROM node:16

# Crea y configura el directorio de trabajo
WORKDIR /usr/src/app

# Copia el archivo package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos
COPY . .

# Expón el puerto
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "run", "start:dev"]